<script>
    url = 'post';
    var postId = 'post-<?= secureEncode($_GET['id']); ?>';
</script>
<div class="page" style="padding-top: 30px;">
<div class="page__content">
    <div class="feed" id="feed">
        <div class="feed-content">

            <!-- FEED -->
            <div class="feed" id="feed">
                <div class="feed-content" id="feed-content" style="display: none;">
                    <?php
                    for ($x = 0; $x < 1; $x++) { ?>          
                        <div class="feed-post" data-loading-feed="<?= $x; ?>">
                            <div class="tile text-post-tile">
                                <div class="feed-my-club__header">
                                </div>
                                <div class="tile-header">
                                    <div>
                                        <a class="avatar-wrapper" href="#">
                                            <span class="avatar model-avatar" style="--avatar-size: 48px; --avatar-border-size: 0px;">
                                                <span class="avatar__img loading-story"></span>
                                            </span>
                                        </a>
                                    </div>
                                    <div class="content-wrapper">

                                    </div>
                                </div>
                                <div class="text-post">
                                    <div class="data-hj-suppress S S--clickable">
                                        <div class="image-swiper">
                                            <div class="image-swiper__scroll" style="height: 325px;">
                                                <div class="image-swiper__item loading-feed" style="width: 100%;height: 325px;">
                                                </div>

                                            </div>
                                        </div>
                                    </div>
                                    <div style="position:relative;margin-top:15px;width: 350px;
                                    height: 30px;">
                                        <div class="loading-feed"></div>
                                    </div>                                                           
                                </div>
                                <div class="tile-footer">
                                    <div class="content" style="height:80px;margin-left: 2px;border:none">
                                        <div class="left-wrapper">
                                            <button class="likes-counter likes-counter--size--medium loading-story" style="width: 32px;">
                                            </button>
                                            <button class="likes-counter likes-counter--size--medium loading-story" style="width: 24px;height:24px;margin-left: 10px;">
                                            </button>
                                            <button class="likes-counter likes-counter--size--medium loading-story" style="width: 32px;margin-left: 10px;">
                                            </button>                                                     
  
                                        </div>
                                        <div class="right-wrapper">
                                            <button class="likes-counter likes-counter--size--medium loading-story" style="width: 32px;margin-left: 10px;">
                                            </button>      
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>                    
                    <?php } ?>

                </div>
            </div>
        </div>
    </div>
</div>
</div>